# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      nodejs: 14  
  pre_build:
    commands:
      - echo Installing source dependencies...
      - npm install
      - $(aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 329511059546.dkr.ecr.ap-southeast-1.amazonaws.com)
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - docker build -t erivera-tier2-ecr .
      - docker tag erivera-tier2-ecr:latest 329511059546.dkr.ecr.ap-southeast-1.amazonaws.com/erivera-tier2-ecr:latest
  post_build:
    commands:
      - echo Pushing the docker image
      - docker push 329511059546.dkr.ecr.ap-southeast-1.amazonaws.com/erivera-tier2-ecr:latest
# Include only the files required for your application to run.
# Do not use recursively include artifacts from node_modules directory as it will include unnecessary packages 
# used only for building and testing.
# ExpressJS apps will need other artifact directories included (bin/*, public/*, routes/*, views/* etc).
artifacts:
  files:
    - index.js
    - package.json
